package version

import (
	"context"
	"time"
)

// Snapshot is the authoritative per-key version state.
// Exists=false means the version store has no current record for the key.
type Snapshot struct {
	Fence  Fence
	Exists bool
}

// Store abstracts where authoritative fences live.
// Use LocalStore (default) for in-process version state, or redis.NewVersionStore
// for distributed version state.
//
// CacheKey values are opaque canonical identities generated by cascache.
// Implementations must treat them as exact bytes and must not try to parse,
// normalize, or reconstruct them from logical user keys.
type Store interface {
	// Snapshot returns the current authoritative version state for a
	// canonical single-key identity.
	Snapshot(ctx context.Context, cacheKey CacheKey) (Snapshot, error)

	// SnapshotMany returns authoritative version state for many canonical
	// single-key identities. Missing keys must be represented as Exists=false.
	SnapshotMany(ctx context.Context, cacheKeys []CacheKey) (map[CacheKey]Snapshot, error)

	// CreateIfMissing creates explicit authoritative state only when the key is
	// currently missing. A created record starts with a fresh fence.
	CreateIfMissing(ctx context.Context, cacheKey CacheKey) (snap Snapshot, created bool, err error)

	// Advance moves authoritative state for a canonical single-key identity to a
	// fresh fence. It must replace any current live fence with a fresh unequal
	// fence. If the key is missing, it creates authoritative state with a fresh
	// fence.
	Advance(ctx context.Context, cacheKey CacheKey) (Snapshot, error)

	// Cleanup prunes old metadata if applicable (no-op for Redis).
	Cleanup(retention time.Duration)

	// Close releases resources (no-op ok).
	Close(context.Context) error
}
