package genstore

import (
	"context"
	"time"
)

// CacheKey is an canonical single-key identity generated by cascache.
// It is not a logical user key and must be treated as exact bytes.
type CacheKey struct {
	raw string
}

// NewCacheKey constructs a canonical cache identity from its exact bytes.
// This is mainly for cascache internals, GenStore implementations, and tests.
// Application code should normally work with logical keys through CAS methods.
func NewCacheKey(raw string) CacheKey {
	return CacheKey{raw: raw}
}

func (k CacheKey) String() string {
	return k.raw
}

// GenStore abstracts where generations live.
// Use LocalGenStore (default) for in-process gens, or redis.NewGenStore for
// distributed gens.
//
// CacheKey values are opaque canonical identities generated by cascache.
// Implementations must treat them as exact bytes and must not try to parse,
// normalize, or reconstruct them from logical user keys.
type GenStore interface {
	// Snapshot returns the current generation for a canonical single-key
	// identity; missing => 0.
	Snapshot(ctx context.Context, cacheKey CacheKey) (uint64, error)

	// SnapshotMany returns gens for many canonical single-key identities.
	// Missing keys map to 0 in the returned map under the same CacheKey values.
	SnapshotMany(ctx context.Context, cacheKeys []CacheKey) (map[CacheKey]uint64, error)

	// Bump atomically increments and returns the new generation for a canonical
	// single-key identity.
	Bump(ctx context.Context, cacheKey CacheKey) (uint64, error)

	// Cleanup prunes old metadata if applicable (no-op for Redis).
	Cleanup(retention time.Duration)

	// Close releases resources (no-op ok).
	Close(context.Context) error
}
