package genstore

// CacheKey is an canonical single-key identity generated by cascache.
// It is not a logical user key and must be treated as exact bytes.
type CacheKey struct {
	raw string
}

// NewCacheKey constructs a canonical cache identity from its exact bytes.
// This is mainly for cascache internals, GenStore implementations, and tests.
// Application code should normally work with logical keys through CAS methods.
func NewCacheKey(raw string) CacheKey {
	return CacheKey{raw: raw}
}

func (k CacheKey) String() string {
	return k.raw
}
